In [53]:
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
import numpy as np

In [5]:

breast_cancer = datasets.load_breast_cancer(as_frame= True)

data = breast_cancer['data']
target = breast_cancer['target']

X_train, X_test, y_train, y_test = train_test_split(breast_cancer['data'], breast_cancer['target'], train_size=0.75, random_state = 1234)

In [15]:
feature_names = breast_cancer['feature_names']
target_names = breast_cancer['target_names']

In [68]:
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)
arbre = clf.tree_
print(arbre)

In [20]:
import graphviz 
tree.export_graphviz(clf, feature_names=feature_names, class_names=target_names, out_file = 'tree.dot')

In [43]:
path = clf.decision_path(X_test.iloc[[100]])
print(path)

  (0, 0)	1
  (0, 22)	1
  (0, 28)	1
  (0, 32)	1


In [81]:
path = clf.decision_path(X_test.iloc[[0]])
print(path)

  (0, 0)	1
  (0, 1)	1
  (0, 2)	1
  (0, 4)	1
  (0, 5)	1
  (0, 6)	1
  (0, 7)	1


In [58]:
n_nodes = clf.tree_.node_count
children_left = clf.tree_.children_left
children_right = clf.tree_.children_right
feature = clf.tree_.feature
threshold = clf.tree_.threshold

X_test_vals = X_test.values
print(X_test_vals)
node_indicator = clf.decision_path(X_test)
leaf_id = clf.apply(X_test)

sample_id = 100
# obtain ids of the nodes `sample_id` goes through, i.e., row `sample_id`
node_index = node_indicator.indices[
    node_indicator.indptr[sample_id] : node_indicator.indptr[sample_id + 1]
]

print("Rules used to predict sample {id}:\n".format(id=sample_id))
for node_id in node_index:
    # continue to the next node if it is a leaf node
    if leaf_id[sample_id] == node_id:
        continue

    # check if value of the split feature for sample 0 is below threshold
    if X_test_vals[sample_id, feature[node_id]] <= threshold[node_id]:
        threshold_sign = "<="
    else:
        threshold_sign = ">"

    print(
        "decision node {node} : (X_test[{sample}, {feature}] = {value}) "
        "{inequality} {threshold})".format(
            node=node_id,
            sample=sample_id,
            feature=feature_names[feature[node_id]],
            value=X_test_vals[sample_id, feature[node_id]],
            inequality=threshold_sign,
            threshold=threshold[node_id],
        )
    )

[[1.167e+01 2.002e+01 7.521e+01 ... 8.120e-02 3.206e-01 8.950e-02]
 [1.080e+01 9.710e+00 6.877e+01 ... 4.603e-02 2.090e-01 7.699e-02]
 [1.245e+01 1.641e+01 8.285e+01 ... 1.342e-01 3.231e-01 1.034e-01]
 ...
 [9.720e+00 1.822e+01 6.073e+01 ... 0.000e+00 1.909e-01 6.559e-02]
 [2.329e+01 2.667e+01 1.589e+02 ... 2.733e-01 3.198e-01 8.762e-02]
 [1.398e+01 1.962e+01 9.112e+01 ... 1.827e-01 3.179e-01 1.055e-01]]
Rules used to predict sample 100:

decision node 0 : (X_test[100, mean concave points] = 0.1265) > 0.051419999450445175)
decision node 22 : (X_test[100, worst perimeter] = 160.0) > 103.25)
decision node 28 : (X_test[100, worst texture] = 33.81) > 20.875)


In [83]:
n_nodes = clf.tree_.node_count
children_left = clf.tree_.children_left
children_right = clf.tree_.children_right
a = clf.tree_
feature = clf.tree_.feature
threshold = clf.tree_.threshold

X_test_vals = X_test.values

res = clf.predict(X_train) 
print(res)
nodes_0 = np.unique(clf.apply(X_train)[res == 0])
nodes_1 = np.unique(clf.apply(X_train)[res == 1])
leaves = np.unique(clf.apply(X_train))
print(nodes_0)
print(nodes_1)
print(children_right)
print(children_left)
print(leaves)

[1 0 1 0 1 0 0 1 1 0 1 1 0 1 0 0 1 1 1 0 1 1 0 1 1 1 1 0 1 1 0 0 1 1 1 1 0
 1 1 1 0 1 0 1 1 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 0 1 1 1 1 0 1 1 1 1 1
 1 0 1 1 1 0 0 1 0 1 0 1 1 1 1 1 1 0 1 0 1 1 1 0 0 0 1 1 1 1 1 1 1 0 1 1 1
 1 0 0 0 0 1 0 1 1 0 0 1 1 1 0 1 1 1 1 0 1 1 0 0 0 1 1 0 1 1 1 1 1 1 1 0 0
 0 0 0 1 1 0 1 1 0 1 0 0 0 1 1 1 0 0 1 0 0 1 1 0 1 0 0 1 1 1 0 1 1 0 1 1 1
 1 1 1 1 1 0 1 1 1 0 1 0 1 0 1 1 0 1 0 0 1 0 1 0 1 1 1 1 1 1 0 1 1 1 0 1 1
 0 1 1 1 1 1 1 0 1 0 1 1 1 1 0 0 1 1 1 1 0 0 0 1 1 0 0 1 0 1 1 1 0 0 1 1 1
 0 1 0 0 1 1 1 1 0 1 0 0 0 1 0 0 0 1 1 1 1 0 1 0 0 0 1 0 1 1 0 0 1 0 0 1 0
 1 0 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 0 0 0 0 1 0 1 1 1 1 0 1 0 1 1 0 1 1
 0 1 0 1 1 1 0 1 1 1 0 1 0 0 0 0 0 1 0 0 1 1 1 0 0 0 1 1 0 1 1 1 1 1 1 1 1
 0 0 1 0 1 0 0 0 1 0 1 0 0 1 0 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0 1 0 1]
[ 3  9 15 18 21 27 31 32]
[ 7 10 12 14 17 20 24 26 30]
[22 19  4 -1 16 11  8 -1 10 -1 -1 13 -1 15 -1 -1 18 -1 -1 21 -1 -1 28 25
 -1 27 

In [91]:
n_nodes = clf.tree_.node_count
children_left = clf.tree_.children_left
children_right = clf.tree_.children_right
feature = clf.tree_.feature
threshold = clf.tree_.threshold

X_test_vals = X_test.values
print(X_test_vals)
node_indicator = clf.decision_path(X_test)
leaf_id = clf.apply(X_test)

sample_id = 0
# obtain ids of the nodes `sample_id` goes through, i.e., row `sample_id`
node_index = node_indicator.indices[
    node_indicator.indptr[sample_id] : node_indicator.indptr[sample_id + 1]
]


def recursive_path(current_node, class_leaves, conditions, path, leaves, current_cond, current_path):
    print(current_node)
    if current_node in leaves:
        if current_node in class_leaves:
            conditions.append(current_cond)
            path.append(current_path)
            current_cond = []
            current_path = []
            return
        else:
            return [],[]
        
    if X_test_vals[sample_id, feature[current_node]] <= threshold[current_node]:
        threshold_sign = "<="
    else:
        threshold_sign = ">"

    cond =  "decision node {node} : (X_test[{sample}, {feature}] = {value}) {inequality} {threshold})".format(
            node=current_node,
            sample=sample_id,
            feature=feature_names[feature[current_node]],
            value=X_test_vals[sample_id, feature[current_node]],
            inequality=threshold_sign,
            threshold=threshold[current_node],
            )
    current_cond.append(cond)
    current_path.append(current_node)
    
    recursive_path(children_left[current_node], class_leaves, conditions, path, leaves, current_cond, current_path)
    recursive_path(children_right[current_node], class_leaves, conditions, path, leaves, current_cond, current_path)
    return conditions, path
    

[[1.167e+01 2.002e+01 7.521e+01 ... 8.120e-02 3.206e-01 8.950e-02]
 [1.080e+01 9.710e+00 6.877e+01 ... 4.603e-02 2.090e-01 7.699e-02]
 [1.245e+01 1.641e+01 8.285e+01 ... 1.342e-01 3.231e-01 1.034e-01]
 ...
 [9.720e+00 1.822e+01 6.073e+01 ... 0.000e+00 1.909e-01 6.559e-02]
 [2.329e+01 2.667e+01 1.589e+02 ... 2.733e-01 3.198e-01 8.762e-02]
 [1.398e+01 1.962e+01 9.112e+01 ... 1.827e-01 3.179e-01 1.055e-01]]


In [92]:

recursive_path(0,nodes_0, [], [], leaves, [], [])

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32


([['decision node 0 : (X_test[0, mean concave points] = 0.02157) <= 0.051419999450445175)',
   'decision node 1 : (X_test[0, worst area] = 550.6) <= 960.5)',
   'decision node 2 : (X_test[0, worst symmetry] = 0.3206) > 0.15654999762773514)',
   'decision node 4 : (X_test[0, worst smoothness] = 0.155) <= 0.17764999717473984)',
   'decision node 5 : (X_test[0, worst perimeter] = 87.0) <= 108.25)',
   'decision node 6 : (X_test[0, worst texture] = 28.81) <= 33.26999855041504)',
   'decision node 8 : (X_test[0, worst texture] = 28.81) <= 33.79999923706055)',
   'decision node 11 : (X_test[0, mean texture] = 20.02) <= 20.994999885559082)',
   'decision node 13 : (X_test[0, mean smoothness] = 0.1016) > 0.09047500044107437)',
   'decision node 16 : (X_test[0, mean concave points] = 0.02157) <= 0.03491500113159418)',
   'decision node 19 : (X_test[0, worst fractal dimension] = 0.0895) > 0.06492000073194504)',
   'decision node 22 : (X_test[0, worst perimeter] = 87.0) <= 103.25)',
   'decision 